services:
  - type: web
    name: livestock-disease-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_SECRET_KEY
        generateValue: true